import {q,getSet} from './db';
import {age,bmi,until} from './notify';
import {download} from './notify';
const iso=d=>new Date(d-d.getTimezoneOffset()*6e4).toISOString().slice(0,10);
const lastDays=n=>Array.from({length:n},(_,i)=>{const d=new Date();d.setDate(d.getDate()-(n-1-i));return iso(d)});
const avg=a=>a.length?a.reduce((x,y)=>x+y,0)/a.length:0,pc=a=>Math.round(avg(a)*100);
const AR={Islam:'#e6c35c',Myself:'#5eead4',Family:'#fb7185'};
function build({H,L,J,score}){
  const D=lastDays(14),cur=D.slice(7),cs=cur.map(d=>score(d)),dl=pc(cs)-pc(D.slice(0,7).map(d=>score(d)));
  const hs=H.map(h=>{const c=cur.filter(d=>L.has(h.id+'|'+d)).length;return {h,c,r:Math.min(1,c/h.per_week)}}).sort((a,b)=>b.r-a.r);
  const moods=cur.map(d=>J[d]?.mood).filter(Boolean),best=cur[cs.indexOf(Math.max(...cs))];
  const note=dl>5?`Up ${dl} points on last week. Whatever you changed, keep it.`:dl<-5?`Down ${-dl} points. A hard week is data, not a verdict. Protect only your top two habits this week.`:'A steady week. Consistency is the quiet form of progress.';
  const nm=getSet('name'),own=getSet('birth'),B=q('select * from body order by day'),W=B.filter(b=>b.weight),inW=W.filter(b=>b.day>=D[7]),base=W.filter(b=>b.day<D[7]).pop()||inW[0],end=inW[inW.length-1],lb=B[B.length-1]||{};
  const BD=q('select * from birthdays').map(b=>({...b,u:until(b.md)})).filter(b=>b.u<=7).sort((a,b)=>a.u-b.u),ou=own?until(own.slice(5)):99;
  const dw=end&&base?end.weight-base.weight:0,bm=bmi(end?.weight||lb.weight,lb.height);
  const body=`<h2>Body and profile</h2><p>${nm}${own?`, age ${age(own)}`:''}${lb.height?`, ${lb.height} cm`:''}.</p><p>${end&&base&&end!==base?`Weight moved from ${base.weight} to ${end.weight} kg (${dw>0?'+':''}${dw.toFixed(1)} this week).`:end?`Weight steady at ${end.weight} kg.`:'No weight logged this week. One entry keeps your trend honest.'}${bm?` BMI ${bm}.`:''}</p>${BD.length||ou<=7?`<h2>Coming up</h2><ul>${ou<=7?`<li>Your birthday ${ou?`in ${ou} days`:'is today'}</li>`:''}${BD.map(b=>`<li>${b.name}'s birthday ${b.u?`in ${b.u} days`:'is today'}</li>`).join('')}</ul>`:''}`;
  const li=x=>`<li>${x.h.name} <i>(${x.c}/${x.h.per_week})</i></li>`;
  return `<!doctype html><meta charset="utf-8"><title>Pathway weekly report</title><style>body{font:16px/1.6 Georgia,serif;background:#0b1020;color:#e8ecf8;max-width:640px;margin:auto;padding:24px}h1{font-size:34px;margin:0}h2{margin:26px 0 6px;font-size:20px;color:#e6c35c}.big{font-size:64px}li{margin:3px 0}i{color:#8a93b2}.bar{height:8px;border-radius:4px;background:#243058}.bar b{display:block;height:100%;border-radius:4px}@media print{body{background:#fff;color:#000}.bar{background:#ddd}}</style>
<h1>Your week in the sky, ${nm}</h1><p><i>${cur[0]} to ${cur[6]}</i></p><div class="big">${pc(cs)}%</div><p>${note}</p>
<svg viewBox="0 0 300 90" width="100%">${cs.map((v,i)=>`<rect x="${i*43+6}" y="${70-v*65}" width="30" height="${v*65+1}" rx="4" fill="${cur[i]===best?'#e6c35c':'#7c9cff'}"/><text x="${i*43+21}" y="86" font-size="10" fill="#8a93b2" text-anchor="middle">${cur[i].slice(5)}</text>`).join('')}</svg>
<p>Your brightest day was <b>${best}</b>.</p><h2>By pole</h2>${Object.keys(AR).map(a=>`<p>${a} ${pc(cur.map(d=>score(d,a)))}%<div class="bar"><b style="width:${pc(cur.map(d=>score(d,a)))}%;background:${AR[a]}"></b></div></p>`).join('')}
<h2>What you did well</h2><ul>${hs.slice(0,4).map(li).join('')}</ul><h2>Needs your love</h2><ul>${hs.slice(-3).map(li).join('')}</ul>
<h2>How it felt</h2><p>${moods.length?`Average mood ${avg(moods).toFixed(1)} out of 5 across ${moods.length} check-ins.`:'No check-ins this week. Try closing the day tonight.'}</p><ul>${cur.filter(d=>J[d]?.note).map(d=>`<li><i>${d}</i> ${J[d].note}</li>`).join('')}</ul>
${body}<p><i>Generated by Pathway.</i></p>`;
}
export default function Report(p){
  const html=build(p);
  return <div className="card"><h3>Weekly report</h3><p className="dim">Written for you from your last 7 days. Open the downloaded file and print it to save as PDF.</p>
    <button className="b" onClick={()=>download(`pathway-week-${iso(new Date())}.html`,html,'text/html')}>Download report</button>
    <iframe title="report" srcDoc={html} style={{width:'100%',height:560,border:0,borderRadius:10,marginTop:10}}/></div>;
}
